services:
  flask_app:
    build: .
    container_name: whisper_app
    restart: always
    expose:
      - 5001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flask.rule=Host(`csort-coffee-bot.ru`)"
      - "traefik.http.routers.flask.entrypoints=websecure"
      - "traefik.http.routers.flask.tls.certresolver=letsencrypt"
      - "traefik.http.services.flask.loadbalancer.server.port=5001"

  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./letsencrypt:/letsencrypt