services:
  flask_app:
    build: .
    container_name: whisper_app
    restart: always
    expose:
      - 5001

  nginx:
    image: nginx:latest
    container_name: whisper_nginx
    restart: always
    ports:
      - "8081:80"  # Using 8081 instead of 80 to avoid conflict with existing nginx
      - "8443:443"  # Added HTTPS port
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl  # Mount SSL certificates
    depends_on:
      - flask_app 